### ISSUE TITLE
Finish feature slogon

### ISSUE THREAD

**Issue by wi1d5ky** [gnumdk/lollypop-web#3]
There are still some dummy texts.

**Comment by wi1d5ky** [comment]
haha... I found @gnumdk has finished that!!

**Comment by bil-elmoussaoui** [comment]
Queue, Replay gain, Search, Party mode, Cover art downloader are repeated twice ?

**Comment by wi1d5ky** [comment]
yes, and I am removing those files....

**Comment by wi1d5ky** [comment]
Done!
The reason of that problem is explained in commit 03eaff5.
